export const ACTION_TYPES = {
  FETCHED_DATA: "FETCHED_DATA",
  TOGGLE_LEFT_CONTAINER:"TOGGLE_LEFT_CONTAINER",
  TOGGLE_RIGHT_CONTAINER:"TOGGLE_RIGHT_CONTAINER",
  TOGGLE_SHEDULING_ICONS:"TOGGLE_SHEDULING_ICONS"
};