export const ACTION_TYPES = {
  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  INPUTBOX_FOCUSED:"INPUTBOX_FOCUSED",
  FETCH_CATEGORY_REQUEST: "FETCH_CATEGORY_REQUEST",
  FETCH_DEFAULT_CATEGORY_REQUEST: "FETCH_DEFAULT_CATEGORY_REQUEST",
  MENU_BUTTON_CLICKED:"MENU_BUTTON_CLICKED",

  CREATE_STEPTASK_REQUEST: "CREATE_STEPTASK_REQUEST",
  MARK_AS_IMPORTANT_TASK_REQUEST:"MARK_AS_IMPORTANT_TASK_REQUEST",
  MARK_AS_COMPLETED_TASK_REQUEST:"MARK_AS_COMPLETED_TASK_REQUEST",
  MARK_AS_COMPLETED_STEPTASK_REQUEST:"MARK_AS_COMPLETED_STEPTASK_REQUEST",
  HIDE_RIGHT_CONTAINER_ICON_CLICKED:"HIDE_RIGHT_CONTAINER_ICON_CLICKED",

  CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",

  FETCH_TASK_REQUEST:"FETCH_TASK_REQUEST",

  GET_UPDATED_DATA:"GET_UPDATED_DATA",
  API_CALL_SUCCESS:"API_CALL_SUCCESS",
  API_CALL_FAILED:"API_CALL_FAILED",
  FETCH_TASK:"FETCH_TASK",
  FETCH_CATEGORY:"FETCH_CATEGORY"
};