export const ACTION_TYPES = {
  NEW_CATEGORY_SUBMITTED: "NEW_CATEGORY_SUBMITTED",
  INPUTBOX_FOCUSED:"INPUTBOX_FOCUSED",
  DYNAMIC_CATEGORY_CLICKED: "DYNAMIC_CATEGORY_CLICKED",
  DEFAULT_CATEGORY_CLICKED: "DEFAULT_CATEGORY_CLICKED",
  MENU_BUTTON_CLICKED:"MENU_BUTTON_CLICKED",

  NEW_STEPTASK_SUBMITTED: "NEW_STEPTASK_SUBMITTED",
  TASK_IMPORTANT_ICON_CLICKED:"TASK_IMPORTANT_ICON_CLICKED",
  TASK_COMPLETED_ICON_CLICKED:"TASK_COMPLETED_ICON_CLICKED",
  STEPTASK_COMPLETED_ICON_CLICKED:"STEPTASK_COMPLETED_ICON_CLICKED",
  HIDE_RIGHT_CONTAINER_ICON_CLICKED:"HIDE_RIGHT_CONTAINER_ICON_CLICKED",

  NEW_TASK_SUBMITTED: "NEW_TASK_SUBMITTED",

  TASK_CLICKED:"TASK_CLICKED",

  GET_UPDATED_DATA:"GET_UPDATED_DATA",
  API_CALL_SUCCESS:"API_CALL_SUCCESS",
  API_CALL_FAILED:"API_CALL_FAILED",
  FETCH_TASK:"FETCH_TASK",
  FETCH_CATEGORY:"FETCH_CATEGORY"
};